services:
  postgres:
    image: postgres:16-alpine
    container_name: gift_shop_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gift_shop
      POSTGRES_USER: gift_shop_user
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: